auto: true
safe: true
#server: true
port: 4000
baseurl: /
url: http://localhost:4000

highlighter: true
#markdown: maruku
markdown: kramdown
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex
